# Цепи Маркова

## Цепи с дискретным временем

In [10]:
import numpy as np
import pprint
import random
from scipy.linalg import expm
np.set_printoptions(precision=5)
pp = pprint.PrettyPrinter(indent=4)

### 1.

In [11]:
P = np.array([[0.1, 0.7, 0.1, 0.1],
             [0, 0, 1, 0],
             [0, 0.8, 0, 0.2],
             [0.1, 0.1, 0.7, 0.1]])
P2 = P

### 2.

In [19]:
power = 50
for i in range(power):
    pp.pprint(np.linalg.matrix_power(P, i))
    print("."*50)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
..................................................
array([[0.     , 0.36364, 0.63636, 0.     ],
       [0.66667, 0.     , 0.11111, 0.22222],
       [0.38095, 0.42857, 0.     , 0.19048],
       [0.     , 0.25   , 0.75   , 0.     ]])
..................................................
array([[0.48485, 0.27273, 0.0404 , 0.20202],
       [0.04233, 0.3456 , 0.59091, 0.02116],
       [0.28571, 0.18615, 0.4329 , 0.09524],
       [0.45238, 0.32143, 0.02778, 0.19841]])
..................................................
array([[0.19721, 0.24413, 0.49036, 0.0683 ],
       [0.45551, 0.27393, 0.08121, 0.18935],
       [0.28901, 0.31323, 0.27393, 0.12382],
       [0.22487, 0.22601, 0.4724 , 0.07672]])
..................................................
array([[0.34956, 0.29894, 0.20385, 0.14765],
       [0.21356, 0.24778, 0.46232, 0.07634],
       [0.31318, 0.25345, 0.31159, 0.12178],
       [0.33064, 

Предельное распределение найдено

## Цепи с непрерывным временем

### 1.

In [13]:
L = np.array([[-4-7, 4, 7, 0],
             [6, -6-1-2, 1, 2],
             [8, 9, -8-9-4, 4],
             [0, 1, 3, -3-1]], dtype=np.float)

### 2.

In [14]:
expm(L*10000)

array([[0.26667, 0.29583, 0.14479, 0.29271],
       [0.26667, 0.29583, 0.14479, 0.29271],
       [0.26667, 0.29583, 0.14479, 0.29271],
       [0.26667, 0.29583, 0.14479, 0.29271]])

Предельное распределение найдено

### 3.

In [15]:
def exp_rand(lmbd, eps):
    return -1/lmbd * np.log(random.random()+eps)

In [16]:
def get_state(i, P):
    p = random.random()
    last = 0
    ans = i
    for j in range(len(P)):
        if last <= p <= last+P[i,j]: 
            ans = j 
            break
        last += P[i,j]
    return ans

In [17]:
def get_p(i,j):
    if i != j:
        return L[i,j]/(-L[i,i])
    else: return 0

In [18]:
eps = 0.0001
T_max = 10000
P = [[],[],[],[]]
for i in range(len(P)):
    for j in range(len(P)):
        P[i].append(get_p(i,j))
P = np.array(P)
print(P)
cur_state = 0
q = np.abs(np.diagonal(L))
times = [exp_rand(q[cur_state], eps), 0, 0, 0]
cur_time = times[cur_state]

while (cur_time <= T_max):
    cur_state = get_state(cur_state, P)
    time_in_state = exp_rand(q[cur_state], eps)
    times[cur_state] += time_in_state
    cur_time += time_in_state
    #print(cur_time)
print("\nState's time: ", times, '\nSummary time: ', sum(times))
ans = [item/sum(times) for item in times]
print('\nStationary distribution: ', ans)

[[0.      0.36364 0.63636 0.     ]
 [0.66667 0.      0.11111 0.22222]
 [0.38095 0.42857 0.      0.19048]
 [0.      0.25    0.75    0.     ]]

State's time:  [2693.484173099102, 2932.2451910685445, 1439.5846678611074, 2934.7437675256665] 
Summary time:  10000.057799554419

Stationary distribution:  [0.26934686049705814, 0.2932228242919955, 0.14395763471739656, 0.29347268049354996]
